[package]
name = "polyglot"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
llm_core = { path = "../llm_core" }
anyhow = "1"
dotenv = "0.15"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
